### ISSUE TITLE
cpp-linter: If no --tidy-checks are specified .clang-tidy file config is overridden

### ISSUE THREAD

**Issue by jenisys** [cpp-linter/cpp-linter#31]
If a `.clang-tidy` exists and you use `cpp-linter` without `--tidy-checks` option,
the default cpp-linter checks are used (`boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*`).
This overrides the `.clang-tidy` checks in this config-file.

## EXPECTED BEHAVIOR
If no `-tidy-checks` option is used, the checks from the `.clang-tidy` config-file should be used.

**Comment by 2bndy5** [comment]
You can pass an empty string instead of omitting the arg. This design decision originated from usage in [cpp-linter-action](https://github.com/cpp-linter/cpp-linter-action).

This has been documented: https://cpp-linter.github.io/cpp-linter/cli_args.html#cmdoption-c

**Comment by jenisys** [comment]
IMHO that is still a bad design decision:

* The user specifies a `.clang-tidy` file
* The tool thinks it knows better when no command-line option is provided

Mmh...

**Comment by 2bndy5** [comment]
Given that cpp-linter-action also sets the same default value: https://github.com/cpp-linter/cpp-linter-action/blob/77982d55693d154611fbb8b1304a447c44ae6f2d/action.yml#L28-L31. I guess we could change the default here to be an empty string.

But if no .clang-tidy file exists and no checks have been specified, then this situation may need further compensation in [`run_clang_tidy()`](https://github.com/cpp-linter/cpp-linter/blob/35e64f8fc02fe982294e940cbba9e79fd5da328c/cpp_linter/run.py#L265) to skip running clang-tidy at all (which can be done by passing `--tidy-checks='-*'`) to avoid needless execution time. I'm not enthusiastic for this change because it would require re-implementing a check for the presence of any relevant .clang-tidy file(s). This presence check would be slower to execute in python and is already done faster with clang-tidy itself; I don't want to "re-invent the wheel".

In the end, it should be noted that this pkg is not clang-tidy. So, we can't be expected to behave exactly like a combination of clang-tidy and clang-format behavior (that would be too brittle).
