### ISSUE TITLE
Filtered file doesn't match any project files

### ISSUE THREAD

**Issue by zjeffer** [cpp-linter/cpp-linter#43]
Sorry for another issue ;)

https://github.com/Alexays/Waybar/actions/runs/7265887999/job/19796540906?pr=2755

```
> Posting comment(s)
DEBUG:CPP Linter:/__w/Waybar/src/modules/hyprland/workspaces.cpp doesn't match any project files
DEBUG:CPP Linter:/__w/Waybar/src/modules/hyprland/workspaces.cpp doesn't match any project files
INFO:CPP Linter:0 clang-format-checks-failed
INFO:CPP Linter:0 clang-tidy-checks-failed
INFO:CPP Linter:0 checks-failed
```

Maybe the `/__w/Waybar/` prefix causes the workspaces.cpp file to not match with the filter? I think it's similar to this issue: https://github.com/cpp-linter/cpp-linter/issues/38#issuecomment-1845532894

**Comment by 2bndy5** [comment]
I made a branch called `process-compilation-database` that crawls the compile_commands.json file (if `database` was specified and the file exists). It first tried to match relative paths found in the database as relative to the compilation unit's directory.

@zjeffer to test it with a meson build, you'll need to either run the cpp-linter package directly after installing from git source:
```
pip install git+https://github.com/cpp-linter/cpp-linter/@process-compilation-database

cpp-linter --database build
``` 
or use a fork of cpp-linter-action that changes the dependency named in requirements.txt:
```diff
-cpp-linter==1.6.4
+git+https://github.com/cpp-linter/cpp-linter/@process-compilation-database
```

---
I'm not enthusiastic about this idea because the fact that meson uses relative paths in their compile_commands.json seems like a problem with meson. However, they don't seem interested in changing that because clang-tools docs state that the database can use either relative or absolute paths... despite that it is just best practice to use absolute paths whenever possible.

**Comment by zjeffer** [comment]
> I'm not enthusiastic about this idea because the fact that meson uses relative paths in their compile_commands.json seems like a problem with meson. However, they don't seem interested in changing that because clang-tools docs state that the database can use either relative or absolute paths... despite that it is just best practice to use absolute paths whenever possible.

I think it's Ninja that does this: https://github.com/mesonbuild/meson/blob/23f831a67497135091bcb44675ff5a7fb9ce8425/mesonbuild/backend/ninjabackend.py#L319

https://gitlab.kitware.com/cmake/cmake/-/issues/17480#note_344177

**Comment by zjeffer** [comment]
The branch works!

![image](https://github.com/cpp-linter/cpp-linter/assets/4633209/4c0386d3-2a8c-441a-a248-ae921a16c522)

https://github.com/Alexays/Waybar/pull/2755/files#diff-57865649be0543861f45b61a80674fabb9efded10e599ad29a40f226b1d66e8f

**Comment by 2bndy5** [comment]
> I think it's Ninja that does this, not necessarily Meson

While meson generates the compile_commands.json, I wasn't aware that ninja prefers relative paths (which boggles my mind -- what about symlinks?)

> The branch works!

I still have to adjust some unit tests (currently failing on that branch) and add yet another unit test that uses a database generated for ninja. I'm not going to lie: I'll probably be dragging my feet on this one.

**Comment by eli-schwartz** [comment]
> While meson generates the compile_commands.json, I wasn't aware that ninja prefers relative paths (which boggles my mind -- what about symlinks?)

Meson does not generate the compile_commands.json -- it executes `ninja -t compdb <rules>`, captures the resulting stdout, and writes it to compile_commands.json.

**Comment by 2bndy5** [comment]
Thanks for the clarification.
